baseURL = 'https://tomfinet.github.io'
languageCode = 'en-us'
title = "Finet - Personal and Dev log"
theme = 'simple-style'
githubURL = 'https://github.com/TomFinet'
author = 'Tom Finet'
search = 'google'
externalLinkIcon = true
externalLinkNewWindow = true
staticDir = 'static'
